export { default as CardServices } from "./card-services/CardServices"
export { default as CaseStudy } from "./case-study/CaseStudy"
export { default as ChooseUs } from "./choose-us/ChooseUs"
export { default as Footer} from "./footer/Footer"
export { default as Header} from "./header/Header"
export { default as NavBar } from "./nav-bar/NavBar"
export { default as Rates } from "./rates/Rates"
export { default as Testimonial } from "./testimonial/Testimonial"
export { default as CTA } from "./cta/CTA"